apiVersion: v1
kind: Service
metadata:
  name: {{ include "c-make-none-git.fullname" . }}
  labels:
    {{- include "c-make-none-git.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "c-make-none-git.selectorLabels" . | nindent 4 }}
